name: Build snaps

env:
  CMAKE_FEATURE_RELEASE: "3.30"
  CMAKE_PATCH_RELEASE: "5"
  CMAKE_RELEASE_SUFFIX: ""
  SNAP_RELEASE_TRACK: stable

on:
  push:
    tags:
      - 'release/**'

jobs:
  build-snap:
    name: Build and publish (${{ matrix.runs-on }})
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, buildjet-2vcpu-ubuntu-2204-arm ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Check out git repo
        uses: actions/checkout@v3
      - name: Apply CMake version to snapcraft.yaml
        run: sed -E 's+@CMAKE_VERSION@+${{ env.CMAKE_FEATURE_RELEASE }}.${{ env.CMAKE_PATCH_RELEASE }}${{ env.CMAKE_RELEASE_SUFFIX }}+g' local/snapcraft.yaml.in > snapcraft.yaml
        working-directory: ./snap
      - name: Build snap
        id: build
        uses: snapcore/action-build@v1
      - name: Publish snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: ${{ env.CMAKE_FEATURE_RELEASE }}/${{ env.SNAP_RELEASE_TRACK }}
